config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'trips#index'

  resources :trips do
    resources :locations, only: [:index, :new, :create, :destroy, :show, :edit, :update]
  end
  
  resources :locations do
    resources :addresses, only: [:index, :new, :create, :update, :destroy, :show, :edit ]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :location
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :trip
  has_one :address, dependent: :destroy
  
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :locations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  has_many :trips
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_location
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  
  def index
    @addresses = @location.address
  end

  def show
  end

  def new
    @address = Address.new
  end
  
  def create
    @address = @location.address.new(address_params)
    if @address.save
      redirect_to trip_location_path(@location.trip_id, @location)
    else
      render :new
    end
  end
  
  def edit
    
  end
  
  def update
    if @address.update(address_params)
      redirect_to location_addresses_path(@location)
    else
      render :edit
    end
  end
  
  def destroy
    @address.destroy
    redirect_to location_address_path(@location)
  end
  
  private
    def set_location
      @location = Location.find(params[:location_id])
    end

    def set_address
      @address = @location.address
    end

    def address_params
      params.require(:address).permit(:street, :city, :state, :zip)
    end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_trip
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  
    def index
      @locations = @trip.locations
    end
  
    def show
    end
  
    def new
      @location = @trip.locations.new
    end
  
    def edit
    end
  
    def create
      @location = @trip.locations.new(location_params)
  
      if @location.save
        redirect_to new_location_address_path(@location)
      else
        render :new
      end
    end
  
    def update
      if @location.update(location_params)
        redirect_to [@trip, @location]
      else
        render :edit
      end
    end
  
    def destroy
      @location.destroy
      redirect_to trip_locations_path
    end
  
    private
      def set_trip
        @trip = Trip.find_by_id(params[:trip_id])
      end
  
      def set_location
        @location = Location.find(params[:id])
      end
  
      def location_params
        params.require(:location).permit(:name)
      end
  end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  
  def index
    @trips = current_user.trips
  end

  def show
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = current_user.trips.new(trip_params)
    if @trip.save
      redirect_to new_trip_location_path(@trip)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @trip.update(trip_params)
      redirect_to trips_path
    else
      render :edit
    end
  end

  def destroy
    @trip.destroy
    redirect_to trips_path
  end

  private
    def trip_params
      params.require(:trip).permit(:name)
    end
    # don't just find by the Trip model or you may potentially be able to view other users accounts
    def set_trip
      @trip = current_user.trips.find(params[:id])
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: [@location, @address], local: true, class: "ui form") do |f| %>

<div class="field">
    <%= f.label :street %>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
   <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>
   <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: 'btn' %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Edit Address</h1>
<%= render 'form', address: @address %>
<%= link_to 'Back', location_addresses_path(@location) %>

app/views/addresses/index.html.erb
<h1>Click a Location To View It</h1>
<%= link_to 'Back To Locations', :back %>
<br />
<br />

  <div>
  <%= @addresses.street %>
  
  <%= @addresses.city %><br />
  <%= @addresses.zip %><br />
  <%= @addresses.state %></li>
  </div>

<%= link_to 'Edit', edit_location_address_path(@location, @addresses) %>
<%= link_to  "Delete", [@address, @location], method: :delete %>

app/views/addresses/new.html.erb
<h1>New Address</h1>
<%= render 'form', address: @address %>
<%= link_to 'Back', location_addresses_path(@location) %>

app/views/addresses/show.html.erb
<p><strong>Addresses</strong></p>
<%= @address.street %>
<%= @address.city %>
<%= @address.zip %>
<%= @address.state %>
<%= link_to  "edit", edit_location_address_path(@location) %>
<%= link_to  "Delete", [@address, @location], method: :delete %>
<%= link_to 'Back', location_address_path(@location) %>

app/views/layouts/_navbar.html.erb
<nav>
  <div class='ui container'>
  <h4>
      <%= link_to 'Trips', trips_path %> |
      <%= link_to 'Add Trip', new_trip_path %> |
      <% if current_user %>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
      <% else %>
      <%= link_to 'Add User', new_user_registration_path %> |
      <%= link_to 'Sign In', new_user_session_path %> |
    <% end %>
    </div>
    </h4>
    <br />
    <br />
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackTrip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class="ui container">
  <%= yield %>
  </div>
  </body>
</html>

app/views/locations/_form.html.erb
<h1><%= @location.id ? 'Edit Location' : 'Create Location' %></h1>
<hr />
<%= form_with(model: [@trip, @location], local: true, class: "ui form") do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  
  <%= f.submit nil, class: "ui button" %>
<% end %>

app/views/locations/edit.html.erb
<%= render "form", location: @location, trip: @trip %>

app/views/locations/index.html.erb
<h1><%= @trip.name %> Locations</h1>

<%= link_to 'New Location', new_trip_location_path %> |
<%= link_to 'Back To Locations', root_path %>

<hr />

<% @locations.each do |location| %>
<table class="ui very basic collapsing celled table">
<thead>
<tr>
</tr>
</thead>


<tbody>
<tr width='100px'>
<td>
<h4 class="ui image header">
<img src="">
<div class="content">
<%= link_to location.name, [@trip, location] %>
<div class="sub header">
<br />
<%= location.address.state %></div>
</div></h4>
</td>

<td>
<%= location.address.street %>
<%= location.address.city %>
<%= location.address.state %>
<%= location.address.zip %>
</td>
</tr>           
</tbody>
</table>

<% end %>

app/views/locations/new.html.erb
<div>
<%= render "form", location: @location %>
</div>
<br />
<%= link_to "Back", trip_locations_path() %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>

<h2>
<%= @location.address.street %>
<%= @location.address.city %>
<%= @location.address.state %>
<%= @location.address.zip %>
</h2>

<br />

<h3>
<%= link_to 'Edit Address', edit_location_address_path(@location) %> |
<%= link_to 'Edit Location', edit_location_path(@location) %> |
<%= link_to 'Delete Location', [@trip, @location], method: :delete %> |
<%= link_to 'Back To Locations', :back %>
</h3>



  

app/views/trips/edit.html.erb
<h1> Trip</h1>
<%= form_with(model: @trip, local: true) do |f| %>
  <div class="field">
  <%= f.label :name %>
  <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <br />
  <div class="field">
  <%= f.submit %>
  </div>
<% end %>

app/views/trips/index.html.erb
<h2>Welcome, <%= current_user.email %></h2>
<h1>Your Trips</h1>
<hr />
<br />

<%= link_to "Add Trip", new_trip_path %>
<br />
<br />
<br />

<div class="ui grid container">
<div class="ui cards">
<% @trips.each do |trip| %>
          <div class="card">
            <div class="content">
               <img class="right floated mini ui image" 
               src="https://cdn5.vectorstock.com/i/1000x1000/12/44/cartoon-travel-plane-doodle-lettering-for-vector-23431244.jpg">
              <div class="header">
                <i><%= link_to trip.name, trip_path(trip) %></i>
              </div>
              <hr />
              <div class="meta">
                <%= link_to 'Locations', trip_locations_path(trip, [:id]) %>
              </div>
              <br />
              <br />
              <div class="description">
              This will be the description
              </div>
            </div>
      
            <div class="extra content">
              <div class="ui two buttons">
                <div class="ui basic green button">
                  <%= link_to 'Edit', edit_trip_path(trip) %>
                </div>
                <div class="ui basic red button">
                  <%= link_to 'Delete', trip_path(trip), method: :delete, data: { confirm: 'Are you sure you want to delete this trip?' } %>
                </div>
              </div>
            </div>
          </div>
          <% end %>
      </div>
    </div>
  </div


    
       
      
      

app/views/trips/new.html.erb
<h1>Add Trip</h1>
<%= form_with(model: @trip, local: true) do |f| %>
  <div class="ui divider"></div>
  <div class="ui-grid">
  <div class="field">
    <%= f.label :"Name:" %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <br />
  <%= f.submit %>
<% end %>

app/views/trips/show.html.erb
<h1><%= @trip.name %></h1>

<%= link_to 'Locations', trip_locations_path(@trip, [:id]) %> |
<%= link_to 'Back To Trips', root_path %>

<hr />

<h2>
This would be the trip description
</h2>